FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "raylib-beef"
TargetType = "BeefLib"
StartupObject = "beef.Program"
DefaultNamespace = "Raylib"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\libs_x64\\raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/libs_x64/*.dll\")"]

[Configs.Debug.wasm32]
OtherLinkFlags = "$(LinkFlags) -s USE_GLFW=3"
LibPaths = ["$(ProjectDir)\\libs\\wasm\\libraylib.a"]

[Configs.Release.Win64]
CLibType = "Dynamic"
LibPaths = ["$(ProjectDir)\\libs\\libs_x64\\raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/libs_x64/*.dll\")"]

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags) -s USE_GLFW=3"
LibPaths = ["$(ProjectDir)\\libs\\wasm\\libraylib.a"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/libs_x64/*.dll\")"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\libs\\libs_x64\\raylibdll.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/libs_x64/*.dll\")"]

[Configs.Debug.Linux64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\linux_x64\\libraylib.so"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/linux_x64/*.so\")"]

[Configs.Release.Linux64]
CLibType = "Dynamic"
LibPaths = ["$(ProjectDir)\\libs\\linux_x64\\libraylib.so"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/linux_x64/*.so\")"]

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)\\libs\\_x64\\libraylib.so"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/linux_x64/*.so\")"]

[Configs.StaticDebug.Linux64]
CLibType = "StaticDebug"
LibPaths = ["$(ProjectDir)\\libs\\linux_x64\\libraylib.a"]

[Configs.StaticRelease.Linux64]
CLibType = "Static"
LibPaths = ["$(ProjectDir)\\libs\\linux_x64\\libraylib.a"]

[Configs.StaticTest.Linux64]
LibPaths = ["$(ProjectDir)\\libs\\_x64\\libraylib.a"]
